"""add person persistence

Revision ID: 39c325d1bd7e
Revises: 74270fc7bf71
Create Date: 2026-09-07 16:49:47.585749

"""

from collections.abc import Sequence
from datetime import date
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39c325d1bd7e"
down_revision: str | Sequence[str] | None = "74270fc7bf71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person_profile",
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("height_cm", sa.Integer(), nullable=False),
        sa.Column("training_goal", sa.String(length=50), nullable=False),
        sa.Column("max_heart_rate_bpm", sa.Integer(), nullable=True),
        sa.Column("start_weight_kg", sa.Float(), nullable=True),
        sa.Column("target_weight_kg", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.PrimaryKeyConstraint("person_id"),
    )

    # Preserve the stable IDs used by existing workouts and check-ins.
    person_table = sa.table(
        "person",
        sa.column("id", sa.Integer()),
        sa.column("display_name", sa.String()),
    )

    op.bulk_insert(
        person_table,
        [
            {"id": 1, "display_name": "Person 1"},
            {"id": 2, "display_name": "Person 2"},
            {"id": 3, "display_name": "Person 3"},
            {"id": 4, "display_name": "Person 4"},
        ],
    )

    # Migrate the values from the previous static PersonProfileService.
    # These are existing defaults, not newly inferred personal data.
    profile_table = sa.table(
        "person_profile",
        sa.column("person_id", sa.Integer()),
        sa.column("date_of_birth", sa.Date()),
        sa.column("height_cm", sa.Integer()),
        sa.column("training_goal", sa.String()),
        sa.column("max_heart_rate_bpm", sa.Integer()),
        sa.column("start_weight_kg", sa.Float()),
        sa.column("target_weight_kg", sa.Float()),
    )

    op.bulk_insert(
        profile_table,
        [
            {
                "person_id": person_id,
                "date_of_birth": date(1980, 1, 1),
                "height_cm": 180,
                "training_goal": "general_fitness",
                "max_heart_rate_bpm": None,
                "start_weight_kg": None,
                "target_weight_kg": None,
            }
            for person_id in range(1, 5)
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_profile")
    op.drop_table("person")
    # ### end Alembic commands ###
