"""add workout video state

Revision ID: 59a7f87cf549
Revises: 0d6027eb0de0
Create Date: 2026-09-06 16:34:45.375008

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59a7f87cf549"
down_revision: str | Sequence[str] | None = "0d6027eb0de0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout",
        sa.Column("video_id", sa.String(), server_default="Lqhq5UQ-U8A", nullable=False),
    )
    op.add_column(
        "workout",
        sa.Column("video_position_seconds", sa.Float(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout", "video_position_seconds")
    op.drop_column("workout", "video_id")
    # ### end Alembic commands ###
