"""add workout video catalog

Revision ID: 74270fc7bf71
Revises: 59a7f87cf549
Create Date: 2026-09-07 09:50:28.853727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74270fc7bf71'
down_revision: Union[str, Sequence[str], None] = '59a7f87cf549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workout_video",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default="1",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        sa.text(
            """
            INSERT INTO workout_video (
                id,
                title,
                description,
                file_path,
                duration_seconds,
                active,
                created_at
            )
            VALUES (
                'cycling-alpen-01',
                'Alpen',
                'Trainingsvideo Alpen',
                'cycling/alpen.mp4',
                NULL,
                1,
                CURRENT_TIMESTAMP
            )
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_video')
    # ### end Alembic commands ###
