"""create initial health coach schema

Revision ID: ad3306bf474c
Revises:
Create Date: 2026-08-25 14:59:25.490851

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad3306bf474c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_in",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("recovery", sa.Integer(), nullable=False),
        sa.Column("muscle_soreness", sa.Integer(), nullable=False),
        sa.Column("stress", sa.Integer(), nullable=False),
        sa.Column("available_training_minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_check_in_person_id"), "check_in", ["person_id"], unique=False)
    op.create_index(op.f("ix_check_in_timestamp"), "check_in", ["timestamp"], unique=False)
    op.create_table(
        "workout",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("total_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("elapsed_seconds", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workout_person_id"), "workout", ["person_id"], unique=False)
    op.create_table(
        "workout_phase",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("workout_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("phase_type", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("target_heart_rate_min", sa.Integer(), nullable=False),
        sa.Column("target_heart_rate_max", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workout.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_phase_workout_id"), "workout_phase", ["workout_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_phase_workout_id"), table_name="workout_phase")
    op.drop_table("workout_phase")
    op.drop_index(op.f("ix_workout_person_id"), table_name="workout")
    op.drop_table("workout")
    op.drop_index(op.f("ix_check_in_timestamp"), table_name="check_in")
    op.drop_index(op.f("ix_check_in_person_id"), table_name="check_in")
    op.drop_table("check_in")
    # ### end Alembic commands ###
